### ISSUE TITLE
Error: Unable to open file '~/Documents/CDDATiled/tiled_cdda_extension.json': No such file or directory

### ISSUE THREAD

**Issue by snipercup** [solerante/tiled-cdda-map-extension#29]
I got this error when using 'Import DDA Tileset':
```
Error: Unable to open file '~/Documents/CDDATiled/tiled_cdda_extension.json': No such file or directory
Stack traceback:
  initialize@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:31
  @file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:924
```

Steps to reproduce:
1. Downloaded Tiles
2. Put the .mjs in ~/.config/tiled/extensions
3. Created a new project in ~/Documents/CDDATiled
4. use the  'Import DDA Tileset' option from the menu

My OS:
![image](https://user-images.githubusercontent.com/50166150/200125502-781c6c90-90c8-43a9-aec0-1b10fc546af3.png)

**Comment by solerante** [comment]
I reproduced this in ubuntu and found the issue (it probably happens in every OS).
It doesn't seem to resolve relative paths, so it doesn't like the "~". I'm not sure how to resolve relative paths in Tiled yet, so the workaround may have to be to use fully-resolved path names in the meantime while I figure it out.

**Comment by snipercup** [comment]
The workaround worked! I used ```/home/user/Documents/GitHub/Cataclysm-DDA-1``` for cdda path and ```/home/user/Documents/CDDATiled``` for the tiled project folder and it executed without error

**Comment by solerante** [comment]
😅 I'm so glad everything didn't immediately fail
