### ISSUE TITLE
Error when exporting my map

### ISSUE THREAD

**Issue by snipercup** [solerante/tiled-cdda-map-extension#52]
I was editing file /home/user/Documents/GitHub/Cataclysm-DDA-1/data/json/mapgen/store/s_camping.json but when I pressed file->export as
![image](https://user-images.githubusercontent.com/50166150/201425909-0ab0e85a-ec2f-4a05-a234-beb83912ff57.png)

This error showed up:

![image](https://user-images.githubusercontent.com/50166150/201425728-872cad62-234b-4f7a-b712-2fc9eaab2e8b.png)

```
TypeError: Cannot call method 'property' of null
Stack traceback:
  prepareEntry@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:826
  prepareExportMap@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:858
  write@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:871
```

The edit of the campsite was a breeze though!

**Comment by snipercup** [comment]
Okay so with the latest version (that introduced cdda_map_extention_extras) I could do a little bit more. I pressed file->export as...
at the first prompt i entered my project folder ```/home/user/Documents/CDDATiled``` and the second prompt i entered my cdda folder: ```/home/user/Documents/GitHub/Cataclysm-DDA-1/```

Afterwards it gave me this error:
```
TypeError: Type error
Stack traceback:
  prepareEntry@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:1000
  prepareExportMap@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:1124
  write@file:///home/user/.config/tiled/extensions/CDDA_Map_extension.mjs:1137
```

**Comment by solerante** [comment]
I'm not sure if what I pushed just now fixes this. I was able to import campsite.json, add some lava, and export it. A far cry from the entire map you've concocted, but perhaps the new mjs fixes it?

**Comment by snipercup** [comment]
I'm doing the same thing but the error shows up
![image](https://user-images.githubusercontent.com/50166150/201443786-832737a0-7d6f-4e36-b8d2-f8c2dd668839.png)

**Comment by solerante** [comment]
I rather like these maps.

I think I have a guess for the cause. If you gather your layers and put them in a Group Layer, and then name that layer what you would like your om_terrain to be, does it let you export?

**Comment by snipercup** [comment]
I'm just messing around but once larger maps are supported I'd like to make a building like a 3d printing service I saw in boston

So I added this group layer
![image](https://user-images.githubusercontent.com/50166150/201448548-8f4c25fd-77ba-4186-8b0a-d8cdf84f41be.png)


It worked!
![image](https://user-images.githubusercontent.com/50166150/201448626-4db32a8d-249f-46e9-990f-564461da86bf.png)
